---
### IMPORTANT this file is generated by terraform from the terragrunt repository
### Do NOT change these values manually from the eks-bootstrapper repository

githubActionsRunnersController:
  authSecret:
    name: ${github_actions_runners_controller_auth_secret_name}

githubActionsRunners:
  serviceAccount:
    name: ${github_actions_runners_serviceaccount_name}
    roleArn: '${github_actions_runners_iam_role_arn}'
  runnerHpa:
    minReplicas: 1
    maxReplicas: 5
  environment: ${environment_name}
  runnerImage: ${github_actions_runners_image_url}:${github_actions_runners_image_tag}
  organization: ${github_organization_name}
  patSecrets: {}
  appSecrets:
    - name: github-app-credentials
      # this needs to match the name defined in externalSecrets.secretStores[0].name
      secretStoreName: ${external_secrets_parameter_store_secret_store_name}
      # either SecretStore or ClusterSecretStore
      secretStoreKind: ${external_secrets_parameter_store_secret_store_kind} 
      creationPolicy: Owner
      deletionPolicy: Delete
      # SSM Parameter Store keys to retrieve necessary values
      githubAppPrivateKeySSMPath: ${github_app_private_key_ssm_path}
      githubAppIdSSMPath: ${github_app_id_ssm_path}
      githubAppInstallationIdSSMPath: ${github_app_installation_id_ssm_path}